config/routes.rb
CanaryCanary::Application.routes.draw do

  get "products/show"

  mount Piggybak::Engine => '/checkout', :as => 'piggybak'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :categories
  resources :products
  match "/search" => "products#search"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    can :manage, Piggybak.config.manage_classes.map(&:constantize)
    Piggybak.config.extra_abilities.each do |extra_ability|
      can extra_ability[:abilities], extra_ability[:class_name].constantize
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :product_categories
  has_many :products, through: :product_categories
  attr_accessible :name
  default_scope order('name ASC')
end

app/models/product.rb
class Product < ActiveRecord::Base
  acts_as_sellable
  has_many :product_categories
  has_many :categories, through: :product_categories
  attr_accessible :code, :description, :image, :name, :price, :sale_price, :piggybak_sellable_attributes
  default_scope order('name ASC')

  def self.home_page_products
    count = self.count
    products=[]
    3.times do |n|
      products << Product.offset(rand(count)).first
    end
    products
  end

  def image_link
    "http://www.candywarehouse.com/#{self.image}"
  end

  def link
    "http://canary.dev/products/#{self.id}"
  end
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_orderer
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :load_categories

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  private
  def load_categories
    @categories = Category.all
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products1 = Product.home_page_products
    @products2 = Product.home_page_products
    @products3 = Product.home_page_products
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end

  def search
    @products = Product.search(params[:q])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.haml
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %tr
    %th
    %th
    %th

  - @categories.each do |category|
    %tr
      %td= link_to 'Show', category
      %td= link_to 'Edit', edit_category_path(category)
      %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
-@category.products.each_slice(3) do |products|
  .row
    -products.each do |product|
      .span3
        .image
          =link_to image_tag(product.image, class: 'thumbnail'), product
        .name
          =link_to product.name, product

app/views/home/index.html.haml
.page-header
  %h2
    Canary Canary
    %small candy company
.tabbable
  %ul.nav.nav-tabs
    %li.active
      %a{href: '#tab1', "data-toggle"=>"tab"}
        Just for you
    %li
      %a{href: '#tab2', "data-toggle"=>"tab"}
        What's New
    %li
      %a{href: '#tab3', "data-toggle"=>"tab"}
        Top Sellers
    %li
      %a{href: '#tab4', "data-toggle"=>"tab"}
        Great Buys
  .tab-content
    .tab-pane.active#tab1
      #igdrec_1
    .tab-pane.active#tab2
      -@products1.each do |product|
        .span3
          .image
            =link_to image_tag(product.image, class: 'thumbnail'), product
          .name
            =link_to product.name, product
    .tab-pane#tab3
      -@products2.each do |product|
        .span3
          .image
            =link_to image_tag(product.image, class: 'thumbnail'), product
          .name
            =link_to product.name, product
    .tab-pane#tab4
      -@products3.each do |product|
        .span3
          .image
            =link_to image_tag(product.image, class: 'thumbnail'), product
          .name
            =link_to product.name, product
=javascript_include_tag "http://canary_820.qa.recs.igodigital.com/a/v2/canary_820/home/recommend.js"

app/views/layouts/_categories.html.haml
%ul.nav.nav-pills.nav-stacked
  -@categories.each do |category|
    %li
      =link_to(category.name, category)

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Canary Canary", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      = link_to 'Register', new_user_registration_path
  %li
    = cart_link
= form_tag '/search', :class => "navbar-search pull-right", :method => :get do
  = text_field_tag :Search, nil, :class => "search-query span3", :placeholder => "Search"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "Canary Canary"
    = javascript_include_tag "http://files.igodigital.com/guided-search/canary_828_v2/igdgs.js"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "http://canary_828_v2.collect.igodigital.com/igdrta.js"
    = csrf_meta_tags
    = yield(:head)
    
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container.navigation
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container-fluid
        .row-fluid
          .span3
            = render 'layouts/categories'
          .span9
            = render 'layouts/messages'
            = yield
      :javascript
        var rtaOrganization = 'canary_828_v2';
        var rtaProductSKU = '#{@product ? @product.id : ''}';
        var rtaCart = '';
        var rtaEmail = '';
        var rtaConvertCart = '';
        var rtaOrderNum = '';
        var rtaCartAmounts = '';
        var rtaCartQuantities = '';
        var rtaReportingSegment1 = '';
        var rtaReportingSegment2 = '';
        var rtaRating = '';
        var rtaSearch = '';
        var rtaCategory = '';
        var rtaSpecial = '';
        addLoadEvent(function() {callRTA();});
      %footer
      / ! end of .container
    / ! end of #main

app/views/products/search.html.haml
.page-header
%h3
  Search Results
  .small "#{@products.count} results found."


-@products.each_slice(3) do |products|
  .row
    -products.each do |product|
      .span3
        .image
          =link_to image_tag("http://www.candywarehouse.com/#{product.image}", class: 'thumbnail'), product
        .name
          =link_to product.name, product

app/views/products/show.html.haml
:javascript
  var rtaRetailer = 'candy_724_v3';
  var rtaProductSKU = '';
  var rtaCart = '#{@product.id}';
  var rtaEmail = '';
  var rtaConvertCart = '';
  var rtaOrderNum = '';
  var rtaCartAmounts = '';
  var rtaCartQuantities = '';
  var rtaReportingSegment1 = '';
  var rtaReportingSegment2 = '';
  var rtaRating = '';
  var rtaSearch = '';
  var rtaCategory = '';
  var rtaSpecial = '';
  addLoadEvent(function() {callRTA();});
%h3=@product.name
.row
  .span4
    =image_tag(@product.image)
  .span3
    %p=@product.description.html_safe
  .span2
    %p=cart_form(@product)

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}